### ISSUE TITLE
Add most popular forms of payment, carriers, default pages

### ISSUE THREAD

**Issue by pingwin02** [pingwin02/prestashop#14]
This issue will keep a history of changes on the store page

**Comment by pingwin02** [comment]
Added carriers
![image](https://github.com/pingwin02/prestashop/assets/108282259/13888d4e-657b-44ea-bd1f-55d778c87a3c)
For a product that costs less than 2000zl
![image](https://github.com/pingwin02/prestashop/assets/108282259/46c77a3b-fa3a-4cc3-97e1-a6325d056817)
For a product that costs more than 2000zl
![image](https://github.com/pingwin02/prestashop/assets/108282259/3cd1998a-c08f-4570-9c83-8d0aab864f27)

**Comment by pingwin02** [comment]
Added addon from przelewy24
https://www.przelewy24.pl/do-pobrania/prestashop
![image](https://github.com/pingwin02/prestashop/assets/108282259/3f7eed9e-6f29-4ea6-b157-4dde30f58e46)

**Comment by pingwin02** [comment]
Updated default presta pages
![image](https://github.com/pingwin02/prestashop/assets/108282259/34c7af1f-3244-49ca-8133-0a46605ffff0)
![image](https://github.com/pingwin02/prestashop/assets/108282259/0d7815b8-299e-436b-b7ee-98c904cee620)

**Comment by pingwin02** [comment]
![image](https://github.com/pingwin02/prestashop/assets/108282259/8c95b54d-7c38-4294-9892-cc44546a8159)
Added default pages

**Comment by pingwin02** [comment]
![image](https://github.com/pingwin02/prestashop/assets/108282259/95562b66-075f-4ba0-92bc-c3142a30e72d)
Added carriers

**Comment by pingwin02** [comment]
![image](https://github.com/pingwin02/prestashop/assets/108282259/c816b2fc-109e-429c-b84b-b6d6165a5609)
Disabled delivery when cart weights more than 50 kg

**Comment by pingwin02** [comment]
![image](https://github.com/pingwin02/prestashop/assets/108282259/69f47ca5-d7a8-4b95-8774-270e84031058)
Added cash on delivery option

**Comment by pingwin02** [comment]
![image](https://github.com/pingwin02/prestashop/assets/108282259/6ac62c62-0ccf-4183-8ca2-256c0beef901)
When shopping cart is worth more than 2,000 zl, free delivery

**Comment by pingwin02** [comment]
![image](https://github.com/pingwin02/prestashop/assets/108282259/d56f7d8f-dc74-42cd-8a23-ff69d981c12e)
If not customer needs to pay

**Comment by pingwin02** [comment]
![image](https://github.com/pingwin02/prestashop/assets/108282259/18b86d46-5a12-480a-b222-3e893ed2e70c)
Updated customer reassurance module

**Comment by rimeger** [comment]
![2023-11-12 095450](https://github.com/pingwin02/prestashop/assets/119046649/2fbb516c-067e-417c-bb7e-a15b4e6bb665)
Added posibillity to download invoice when state of order is "Oczekiwanie na płatność przy odbiorze

**Comment by pingwin02** [comment]
Everything done in last page backup
