### ISSUE TITLE
Add mail support

### ISSUE THREAD

**Issue by pingwin02** [pingwin02/prestashop#15]

**Comment by rysiekpol** [comment]
![368511545_302325189379270_3674724583903809631_n](https://github.com/pingwin02/prestashop/assets/49917065/b3b67bbb-b06b-48f5-8bc7-3dcfeddaa8de)
![385532798_1059568045347076_7256655391892312900_n](https://github.com/pingwin02/prestashop/assets/49917065/2f4ceaa9-8bf9-459a-8ea4-17f7f6b2dd80)
![385531266_7003836749637130_7077617873822451957_n](https://github.com/pingwin02/prestashop/assets/49917065/ce74bf2f-dcdb-48bd-84da-24f49eb7cf86)

**Comment by rysiekpol** [comment]
![image](https://github.com/pingwin02/prestashop/assets/49917065/13a2f96f-6830-4574-9e5d-488aad8003c3)
