### ISSUE TITLE
Change frontend of prestashop

### ISSUE THREAD

**Issue by rysiekpol** [pingwin02/prestashop#9]

**Comment by prosto20025** [comment]
![PhotoFront1](https://github.com/pingwin02/prestashop/assets/116769030/d1017f87-cc07-449b-9bfd-89c93c2851c0)
![PhotoFront2](https://github.com/pingwin02/prestashop/assets/116769030/912bd8bb-b72e-4a7f-ad19-d76eee118b5f)
![PhotoFront3](https://github.com/pingwin02/prestashop/assets/116769030/f049136b-6f37-4e4d-a870-931e93d043f4)
![PhotoFront4](https://github.com/pingwin02/prestashop/assets/116769030/7f23a363-a059-4f0b-b3e9-f78c6052c4b3)

Changed main's page look, add new banners and images related with our website. Added variants for a some products with different image depending on variant and also special offers.

**Comment by pingwin02** [comment]
![image](https://github.com/pingwin02/prestashop/assets/108282259/daf7782e-24e8-4c0b-ac0d-73fce9ea9282)
Changed main page header links
